spring:
  datasource:
    url: "jdbc:mysql://127.0.0.1:3306/dinetogether?useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=Asia/Seoul"
    username: "dinetogether"
    password: "1234"
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
